name: Docker Image CI for latest from master

on:
  push:
    branches: ['master']

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker layer caching
      uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag meggsimum/geoserver:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push the Docker image
      run: docker push meggsimum/geoserver:latest
