name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v2.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set ENV for tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Echo tag
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag meggsimum/geoserver:${{ env.RELEASE_VERSION }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push the Docker image
      run: docker push meggsimum/geoserver:${{ env.RELEASE_VERSION }}
